version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: madecomfyau/node-aws:10

jobs:
  configure:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-yarn-cache-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-yarn-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-yarn-cache-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn lint
      - run: yarn test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - configure:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - configure
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - configure
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
